### ISSUE TITLE
您好，我有一些问题

### ISSUE THREAD

**Issue by chengbaitai** [F-windyy/DGATDDI#1]
您好！我在先前也想过药物单向关系的问题，您的工作给了我很大启发，但是我仍有一些不懂的问题，希望您能指教
1.您是怎么抽取出单向关系的？
        您是以DrugBank中的一个drug条目作为source ，下面所有DDI关系涉及到的其他药物当作target对吗？
2.  三元组是否默认具有方向？
        以往的DDI预测任务比如DeepDDI，数据集是以三元组形式存储的，而三元组默认就是有向图。而您的方法是判断两个药物之间u-v之间是否具有单向关系对吗？那么这和给定药物u,v，判断是否存在互作关系的二分类任务（KGNN,MUFFIN之类)区别在哪里呢？
3.  二元分类中单向关系的问题
        如果2理解没错的话，您的任务应该是预测u->v是否存在关系对吗？那么对于二元分类问题，您是怎么定义A对B有单向关系的呢？对于 DB04571   may increase the photosensitizing activities of DB00460. 这个实例，DB04571 对 DB00460是存在关系的毋庸置疑，反之也是存在关系的吧？如果不考虑关系类型的话怎么会存在A对B有作用，而B对A没有作用这样的关系呢？

非常抱歉打扰，十分期待您的回复

**Comment by F-windyy** [comment]
1.并不是，是根据语义关系进行建模的。对于DB04571 may increase the photosensitizing activities of DB00460这样一个实例，DB04571作为source而DB00460作为target。
2.对于标签是u->v的药物对，假设有v->u的样本，其他二分类任务会认为是正样本，因为它们建模为无向图，我们建模成有向图，负样本。DeepDDI虽然是三元组的形式存储，但它并不会出现u->v是正样本而v->u是负样本的情况，实际上还是无向图的建模方式。
3.传统DDI研究是基于药物对双方都会有作用，但是通过一些文献的调研，我们发现可能会存在仅有作为target的药物受到了影响（如文中引用[4]），因此有向图的建模方式（即连边方向可能存在u->v，u<-v，u<->v）实际上是要比无向图（只存在u-v）更加合理的。

**Comment by chengbaitai** [comment]
> 1.并不是，是根据语义关系进行建模的。对于DB04571 may increase the photosensitizing activities of DB00460这样一个实例，DB04571作为source而DB00460作为target。 2.对于标签是u->v的药物对，假设有v->u的样本，其他二分类任务会认为是正样本，因为它们建模为无向图，我们建模成有向图，负样本。DeepDDI虽然是三元组的形式存储，但它并不会出现u->v是正样本而v->u是负样本的情况，实际上还是无向图的建模方式。 3.传统DDI研究是基于药物对双方都会有作用，但是通过一些文献的调研，我们发现可能会存在仅有作为target的药物受到了影响（如文中引用[4]），因此有向图的建模方式（即连边方向可能存在u->v，u<-v，u<->v）实际上是要比无向图（只存在u-v）更加合理的。

我懂您的意思了！非常感谢您的回复
